# Generated by Django 4.2.1 on 2024-04-06 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=400)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='WEBSITE.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen_producto',
            fields=[
                ('id_imagen_p', models.AutoField(db_column='id_imagen_p', primary_key=True, serialize=False)),
                ('imagen_producto', models.FileField(null=True, upload_to='productos/')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='WEBSITE.producto')),
            ],
        ),
    ]
