# Generated by Django 4.1.9 on 2024-05-03 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WEBSITE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(db_column='id_carrito', default=None, primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(db_column='usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(db_column='id_envio', default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Pendiente', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(db_column='id_marca', primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='cant_inventario',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='id_pedido', default=None, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('id_carrito', models.ForeignKey(db_column='id_carrito', default=None, on_delete=django.db.models.deletion.CASCADE, to='WEBSITE.carrito')),
                ('id_envio', models.ForeignKey(db_column='id_envio', on_delete=django.db.models.deletion.CASCADE, to='WEBSITE.estado')),
                ('usuario', models.ForeignKey(db_column='usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Info_cliente',
            fields=[
                ('id_info', models.AutoField(db_column='id_info', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('rut', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=80)),
                ('usuario', models.ForeignKey(db_column='usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, null=True)),
                ('id_carrito', models.ForeignKey(db_column='id_carrito', default=None, on_delete=django.db.models.deletion.CASCADE, to='WEBSITE.carrito')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='WEBSITE.producto')),
            ],
        ),
    ]
