# Generated by Django 4.1.9 on 2024-05-03 22:31

import WEBSITE.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0002_carrito_estado_marca_producto_cant_inventario_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_marca',
            field=models.ForeignKey(db_column='id_marca', default=WEBSITE.models.Marca.get_, on_delete=django.db.models.deletion.CASCADE, to='WEBSITE.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', default=1, on_delete=django.db.models.deletion.CASCADE, to='WEBSITE.categoria'),
        ),
    ]
