# Generated by Django 4.1.9 on 2024-05-21 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WEBSITE', '0002_alter_carrito_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(db_column='id_direccion', default=None, primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=200)),
                ('numeracion', models.IntegerField(default=None)),
                ('comuna', models.CharField(default=None, max_length=100)),
                ('region', models.CharField(default=None, max_length=100)),
                ('usuario', models.ForeignKey(db_column='usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
