# Generated by Django 4.1.9 on 2024-05-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0003_producto_id_marca_alter_producto_id_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_marca',
            field=models.ForeignKey(db_column='id_marca', default=1, on_delete=django.db.models.deletion.CASCADE, to='WEBSITE.marca'),
        ),
    ]
