# Generated by Django 5.0.7 on 2024-07-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0004_alter_carrito_item_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito_item',
            name='cantidad',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
